# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.TextField(blank=True)),
                ('data_cadastro', models.DateField()),
                ('despesa_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.TextField(blank=True)),
                ('data_admissao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.CharField(choices=[('C', 'Chefe'), ('M', 'Master'), ('J', 'Jedi')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
