# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='despesa_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
