# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0002_auto_20170626_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
