# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0003_quarto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Ocupado'), (3, 'Em faxina')]),
        ),
    ]
