# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0004_auto_20170629_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='estado',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Ocupado', 'Ocupado'), ('Em faxina', 'Em faxina')], max_length=20),
        ),
    ]
